import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'theme/app_theme.dart';
import '../features/home/presentation/home_page.dart';
import '../features/friends/presentation/friends_page.dart';
import '../features/activity/presentation/notifications_page.dart';
import '../features/profile/presentation/profile_page.dart';

class AppShell extends StatefulWidget { const AppShell({super.key,required this.initialIndex}); final int initialIndex; @override State<AppShell> createState()=>_AppShellState(); }
class _AppShellState extends State<AppShell>{late int index;static const labels=['Home','Friends','Activity','Profile','Worker House'];static const icons=[Icons.home_outlined,Icons.people_outline,Icons.notifications_none,Icons.person_outline,Icons.work_outline];@override void initState(){super.initState();index=widget.initialIndex;} Widget _page()=>switch(index){0=>const HomePage(),1=>const FriendsPage(),2=>const NotificationsPage(),3=>const ProfilePage(),_=>Center(child:Text(labels[index],style:Theme.of(context).textTheme.headlineSmall))};@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(bottom:false,child:_page()),bottomNavigationBar:SafeArea(minimum:const EdgeInsets.fromLTRB(8,0,8,8),child:Container(height:56,padding:const EdgeInsets.all(5),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:AppTheme.border),boxShadow:const[BoxShadow(blurRadius:24,offset:Offset(0,10),color:Color(0x3D0F172A))]),child:Row(children:[for(var i=0;i<labels.length;i++)Expanded(child:_Destination(selected:index==i,icon:icons[i],label:labels[i],onTap:(){setState(()=>index=i);context.go(['/home','/friends','/activity','/profile','/worker-house'][i]);}))]))));}}
class _Destination extends StatelessWidget{const _Destination({required this.selected,required this.icon,required this.label,required this.onTap});final bool selected;final IconData icon;final String label;final VoidCallback onTap;@override Widget build(BuildContext context)=>InkWell(borderRadius:BorderRadius.circular(13),onTap:onTap,child:Container(margin:const EdgeInsets.symmetric(horizontal:2),decoration:selected?BoxDecoration(gradient:const LinearGradient(colors:[Color(0xff4f46e5),Color(0xff7c3aed),Color(0xff0891b2)]),borderRadius:BorderRadius.circular(13)):null,child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:18,color:selected?Colors.white:AppTheme.textSecondary),const SizedBox(height:1),Text(label,maxLines:1,overflow:TextOverflow.ellipsis,style:TextStyle(fontSize:8,fontWeight:FontWeight.w800,color:selected?Colors.white:AppTheme.textSecondary))])));}}
