import 'dart:async';
import 'package:flutter/material.dart';
import '../../../core/supabase/supabase_client.dart';
import '../data/chat_repository.dart';

class InboxPage extends StatefulWidget {
  const InboxPage({super.key});
  @override State<InboxPage> createState() => _InboxPageState();
}
class _InboxPageState extends State<InboxPage> {
  final repo = ChatRepository(SupabaseClientProvider.client);
  final controller = TextEditingController();
  Map<String,dynamic>? data; String? selected; String search=''; StreamSubscription? sub;
  @override void initState(){super.initState();_load(); sub=SupabaseClientProvider.client.channel('work-social-chat-ui').onPostgresChanges(event:'*',schema:'public',table:'messages',callback:(_)=>_load()).subscribe();}
  Future<void> _load() async {try{final d=await repo.load();if(mounted)setState(()=>data=d);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}}
  @override void dispose(){sub?.cancel();controller.dispose();super.dispose();}
  @override Widget build(BuildContext context){final cs=List<Map<String,dynamic>>.from(data?['conversations']??[]);final messages=List<Map<String,dynamic>>.from(data?['messages']??[]);final profiles=List<Map<String,dynamic>>.from(data?['profiles']??[]);final urls=Map<String,String>.from(data?['media']??{});final filtered=cs.where((c){final q=search.trim().toLowerCase();return q.isEmpty||(c['title']??'').toString().toLowerCase().contains(q);}).toList();return Scaffold(backgroundColor:const Color(0xfff7f8fc),body:SafeArea(child:Row(children:[SizedBox(width:150,child:Column(children:[const Padding(padding:EdgeInsets.all(16),child:Text('Inbox',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900))),Padding(padding:const EdgeInsets.symmetric(horizontal:10),child:TextField(onChanged:(v)=>setState(()=>search=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Search'))),Expanded(child:ListView(children:[for(final c in filtered)ListTile(selected:c['id']==selected,title:Text(c['title']??'Conversation'),onTap:()=>setState(()=>selected=c['id'] as String))]))])),Expanded(child:selected==null?const Center(child:Text('Select a conversation')):_Chat(messages:messages.where((m)=>m['conversation_id']==selected).toList(),profiles:profiles,urls:urls,controller:controller,onSend:()async{final t=controller.text.trim();if(t.isEmpty)return;await repo.sendText(selected!,t);controller.clear();await _load();}))]))));}
}
class _Chat extends StatelessWidget {
  const _Chat({required this.messages,required this.profiles,required this.urls,required this.controller,required this.onSend});
  final List<Map<String,dynamic>> messages,profiles; final Map<String,String> urls; final TextEditingController controller; final Future<void> Function() onSend;
  String _name(String id){for(final p in profiles){if(p['id']==id)return (p['display_name']??p['username']??'User').toString();}return 'User';}
  @override Widget build(BuildContext context)=>Column(children:[Expanded(child:ListView.builder(padding:const EdgeInsets.all(16),itemCount:messages.length,itemBuilder:(context,index){final m=messages[index];final content=(m['content']??'').toString();final legacy=ChatRepository.parseLegacyMedia(content);final path=(m['media_path'] as String?)??legacy?.path;final url=path==null?null:urls[path];final mime=(m['media_mime']??legacy?.mime??'').toString();return Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),boxShadow:const [BoxShadow(blurRadius:14,color:Color(0x160f172a))]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(_name(m['sender_id'] as String),style:const TextStyle(fontWeight:FontWeight.w700)),if(url!=null&&mime.startsWith('image/'))Padding(padding:const EdgeInsets.only(top:8),child:ClipRRect(borderRadius:BorderRadius.circular(12),child:Image.network(url,fit:BoxFit.cover))),if(url!=null&&mime.startsWith('video/'))const Padding(padding:EdgeInsets.only(top:8),child:ListTile(leading:Icon(Icons.play_circle_fill),title:Text('Video attachment'))),if(url!=null&&!mime.startsWith('image/')&&!mime.startsWith('video/'))Padding(padding:const EdgeInsets.only(top:8),child:ListTile(contentPadding:EdgeInsets.zero,leading:const Icon(Icons.insert_drive_file_outlined),title:Text('File attachment'),subtitle:Text('Tap to download'))),if(content.isNotEmpty&&!content.startsWith('__work_social_media__:'))Padding(padding:const EdgeInsets.only(top:8),child:Text(content))]));})),SafeArea(child:Padding(padding:const EdgeInsets.all(10),child:Row(children:[Expanded(child:TextField(controller:controller,onSubmitted:(_)=>onSend(),decoration:const InputDecoration(hintText:'Message...'))),IconButton(onPressed:onSend,icon:const Icon(Icons.send))])))]);
}
