import 'package:flutter/material.dart';
import '../../../core/supabase/supabase_client.dart';
import '../../../app/theme/app_theme.dart';
import '../../posts/data/post_repository.dart';
import '../../posts/presentation/create_post_card.dart';

class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage>{
 late final PostRepository _repository; late Future<List<Map<String,dynamic>>> _posts;
 @override void initState(){super.initState();_repository=PostRepository(SupabaseClientProvider.client);_posts=_repository.fetchPublicPosts();}
 Future<void> _reload()async{setState(()=>_posts=_repository.fetchPublicPosts());await _posts;}
 @override Widget build(BuildContext context)=>RefreshIndicator(onRefresh:_reload,child:CustomScrollView(slivers:[
  SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(16,14,16,6),child:_Header(onSignOut:()=>SupabaseClientProvider.client.auth.signOut()))),
  SliverPadding(padding:const EdgeInsets.fromLTRB(16,10,16,4),sliver:SliverToBoxAdapter(child:CreatePostCard(onCreated:_reload))),
  FutureBuilder<List<Map<String,dynamic>>>(future:_posts,builder:(context,s){if(s.connectionState==ConnectionState.waiting)return const SliverFillRemaining(child:Center(child:CircularProgressIndicator()));if(s.hasError)return SliverFillRemaining(child:Center(child:Text('Unable to load posts.')));final posts=s.data??[];if(posts.isEmpty)return const SliverFillRemaining(child:Center(child:Text('No public posts yet.')));return SliverPadding(padding:const EdgeInsets.fromLTRB(16,10,16,100),sliver:SliverList.separated(itemCount:posts.length,separatorBuilder:(_,__)=>const SizedBox(height:12),itemBuilder:(_,i)=>PostCard(post:posts[i])));})
 ]));
}
class _Header extends StatelessWidget{const _Header({required this.onSignOut});final VoidCallback onSignOut;@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.fromLTRB(18,17,10,17),decoration:BoxDecoration(gradient:AppTheme.brandGradient,borderRadius:BorderRadius.circular(22),boxShadow:const[BoxShadow(blurRadius:28,offset:Offset(0,12),color:Color(0x332F2A85))]),child:Row(children:[Container(width:38,height:38,decoration:BoxDecoration(color:Colors.white.withValues(alpha:.18),shape:BoxShape.circle,border:Border.all(color:Colors.white24)),child:const Icon(Icons.workspaces_rounded,color:Colors.white)),const SizedBox(width:11),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('WORK SOCIAL',style:TextStyle(color:Colors.white,fontSize:12,fontWeight:FontWeight.w900,letterSpacing:2)),SizedBox(height:2),Text('Home',style:TextStyle(color:Colors.white,fontSize:21,fontWeight:FontWeight.w900))])),IconButton(onPressed:onSignOut,tooltip:'Sign out',icon:const Icon(Icons.logout_rounded,color:Colors.white))]));}
class PostCard extends StatelessWidget{const PostCard({super.key,required this.post});final Map<String,dynamic> post;@override Widget build(BuildContext context){final p=post['profiles'] is Map?Map<String,dynamic>.from(post['profiles']):<String,dynamic>{};final name=(p['display_name']??p['username']??'Work Social user').toString();final avatar=p['avatar_url'] as String?;final content=(post['content']??'').toString();final location=(post['location_name']??'').toString();final attachments=post['attachments'] is List?List<Map<String,dynamic>>.from((post['attachments'] as List).map((x)=>Map<String,dynamic>.from(x))):<Map<String,dynamic>>[];return Card(child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[CircleAvatar(radius:23,backgroundImage:avatar?.isNotEmpty==true?NetworkImage(avatar!):null,child:avatar?.isNotEmpty==true?null:Text(name.isEmpty?'?':name[0].toUpperCase())),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:const TextStyle(fontWeight:FontWeight.w850,fontSize:14)),const SizedBox(height:2),Text('@${p['username']??'user'}',style:const TextStyle(color:AppTheme.textSecondary,fontSize:12,fontWeight:FontWeight.w600))])),Container(padding:const EdgeInsets.symmetric(horizontal:8,vertical:5),decoration:BoxDecoration(color:const Color(0x106D5DFC),borderRadius:BorderRadius.circular(99)),child:const Text('PUBLIC',style:TextStyle(color:AppTheme.brand,fontSize:9,fontWeight:FontWeight.w900,letterSpacing:.6)))]),if(content.isNotEmpty)...[const SizedBox(height:14),Text(content,style:const TextStyle(fontSize:15,height:1.45,color:AppTheme.textPrimary))],if(attachments.isNotEmpty)...[const SizedBox(height:12),_AttachmentGrid(items:attachments)],if(location.isNotEmpty)...[const SizedBox(height:10),Row(children:[const Icon(Icons.location_on_outlined,size:17,color:AppTheme.brand),const SizedBox(width:4),Flexible(child:Text(location,style:const TextStyle(color:AppTheme.textSecondary,fontSize:12,fontWeight:FontWeight.w600)))])],const SizedBox(height:12),const Divider(height:1),const SizedBox(height:5),Row(children:[_Action(icon:Icons.favorite_border,label:'Like'),_Action(icon:Icons.chat_bubble_outline,label:'Comment'),_Action(icon:Icons.share_outlined,label:'Share')])])));}}
class _AttachmentGrid extends StatelessWidget{const _AttachmentGrid({required this.items});final List<Map<String,dynamic>> items;@override Widget build(BuildContext c)=>ClipRRect(borderRadius:BorderRadius.circular(16),child:GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:items.length,itemBuilder:(_,i){final a=items[i];final url=a['public_url']?.toString();final kind=a['kind']?.toString();if(url!=null&&url.isNotEmpty&&kind=='image')return Image.network(url,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const ColoredBox(color:Color(0xffeef2ff),child:Icon(Icons.broken_image_outlined)));return Container(color:const Color(0xfff1f5f9),padding:const EdgeInsets.all(14),child:Row(children:[Icon(kind=='video'?Icons.videocam_outlined:Icons.insert_drive_file_outlined,color:AppTheme.brand),const SizedBox(width:8),Expanded(child:Text(a['file_name']?.toString()??'Attachment',maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:12))) ]));},gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:items.length==1?1:2,crossAxisSpacing:3,mainAxisSpacing:3,childAspectRatio:items.length==1?1.7:1.2));}
class _Action extends StatelessWidget{const _Action({required this.icon,required this.label});final IconData icon;final String label;@override Widget build(BuildContext c)=>Expanded(child:InkWell(borderRadius:BorderRadius.circular(12),onTap:(){},child:Padding(padding:const EdgeInsets.symmetric(vertical:9),child:Row(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(icon,size:17,color:AppTheme.textSecondary),const SizedBox(width:5),Text(label,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w800,color:AppTheme.textSecondary))]))));}
