import 'package:flutter/material.dart';
import '../../../core/supabase/supabase_client.dart';
import '../data/notifications_repository.dart';

class NotificationsPage extends StatefulWidget { const NotificationsPage({super.key}); @override State<NotificationsPage> createState()=>_NotificationsPageState(); }
class _NotificationsPageState extends State<NotificationsPage>{
 final repo=NotificationsRepository(SupabaseClientProvider.client); List<Map<String,dynamic>> items=[]; String? error; bool loading=true; RealtimeChannel? channel;
 @override void initState(){super.initState();_load();channel=repo.subscribe(_load);}
 @override void dispose(){if(channel!=null)SupabaseClientProvider.client.removeChannel(channel!);super.dispose();}
 Future<void> _load()async{try{final data=await repo.load();if(mounted)setState(()=>items=data);}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>loading=false);}}
 String label(String t)=>{'friend_request':'sent you a friend request','friend_accept':'accepted your friend request','like':'liked your post','comment':'commented on your post','comment_reply':'replied to your comment','mention_post':'mentioned you in a post','mention_comment':'mentioned you in a comment','follow':'started following you','message':'sent you a message'}[t]??'sent you a notification';
 String icon(String t)=>{'friend_request':'👥','friend_accept':'🤝','like':'❤️','comment':'💬','comment_reply':'↩️','mention_post':'@','mention_comment':'@','follow':'✨','message':'💌'}[t]??'🔔';
 @override Widget build(BuildContext context){final unread=items.where((x)=>x['is_read']!=true).length;return ListView(padding:const EdgeInsets.fromLTRB(16,18,16,110),children:[Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Notifications',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900)),Container(margin:const EdgeInsets.only(top:7),padding:const EdgeInsets.symmetric(horizontal:9,vertical:4),decoration:BoxDecoration(color:const Color(0x164f46e5),borderRadius:BorderRadius.circular(999)),child:Text(unread>0?'$unread unread':'All caught up',style:const TextStyle(color:Color(0xff4f46e5),fontSize:12,fontWeight:FontWeight.w700))) ])),TextButton(onPressed:unread==0?null:()async{await repo.markAllRead();await _load();},child:const Text('Mark all read'))]),if(error!=null)Text(error!,style:const TextStyle(color:Color(0xffb4233c))),if(loading)const Padding(padding:EdgeInsets.all(30),child:Center(child:CircularProgressIndicator())),if(!loading&&items.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Column(children:[Text('🔔',style:TextStyle(fontSize:30)),Text('No notifications yet.')])) ,...items.map(_item)]);}
 Widget _item(Map<String,dynamic> n){final s=n['sender'] as Map<String,dynamic>?;final read=n['is_read']==true;return InkWell(onTap:()async{await repo.markRead(n['id']);await _load();},child:Container(margin:const EdgeInsets.only(top:9),padding:const EdgeInsets.all(11),decoration:BoxDecoration(borderRadius:BorderRadius.circular(15),color:Colors.white,border:Border.all(color:read?const Color(0x14000000):const Color(0x384f46e5)),boxShadow:const[BoxShadow(blurRadius:16,color:Color(0x0b000000),offset:Offset(0,5))]),child:Row(children:[CircleAvatar(radius:22,backgroundImage:(s?['avatar_url'] as String?)?.isNotEmpty==true?NetworkImage(s!['avatar_url']):null,child:(s?['avatar_url'] as String?)?.isNotEmpty==true?null:const Text('👤')),const SizedBox(width:11),Expanded(child:Text('${s?['display_name']??s?['username']??'Someone'} ${label(n['type']??'')}')),Text(icon(n['type']??'')),if(!read)const Padding(padding:EdgeInsets.only(left:8),child:Icon(Icons.circle,size:8,color:Color(0xff4f46e5))) ])));}
}
